export type DataEntryTemplateSection = {
  key: string;
  label: string;
  type: 'RECEITA' | 'DESPESA';
  categoryName: string;
  rows: Array<{ key: string; label: string }>;
};

export const DATA_ENTRY_TEMPLATE: DataEntryTemplateSection[] = [
  {
    key: 'receita',
    label: 'Faturamento',
    type: 'RECEITA',
    categoryName: 'FATURAMENTO',
    rows: [{ key: 'faturamento', label: 'Faturamento (Receita)' }],
  },
  {
    key: 'proteinas',
    label: 'Proteinas',
    type: 'DESPESA',
    categoryName: 'PROTEINAS',
    rows: [
      { key: 'central', label: 'Central' },
      { key: 'bonna_vitta', label: 'Bonna Vitta' },
      { key: 'frigo_peixao', label: 'Frigo Peixao' },
      { key: 'fpl_comercio', label: 'F P L Comercio' },
      { key: 'jg_pescado', label: 'JG Pescado' },
    ],
  },
  {
    key: 'estivas',
    label: 'Estivas',
    type: 'DESPESA',
    categoryName: 'ESTIVAS',
    rows: [
      { key: 'central', label: 'Central' },
      { key: 'ichiban', label: 'Ichiban' },
      { key: 'ebd_empresa_brasileira', label: 'EBD - Empresa Brasileira' },
      { key: 'nestle_brasil', label: 'Nestle Brasil' },
      { key: 'amaro_correa', label: 'Amaro e Correa Ltda' },
      { key: 'vitta_norte', label: 'Vitta Norte da Amazonia' },
      { key: 'jaboao_tomaz', label: 'Jaboao Tomaz' },
      { key: 'distribuidora_farias', label: 'Distribuidora Farias' },
      { key: 'mesa_viana_foods', label: 'Mesa Viana Foods' },
      { key: 'atack', label: 'Atack (CDL Centro Distr)' },
      { key: 'distribuidora_lopes', label: 'Distribuidora Lopes' },
      { key: 'abrahao_souza', label: 'Abrahao de Souza' },
    ],
  },
  {
    key: 'hortifrut',
    label: 'Hortifrut',
    type: 'DESPESA',
    categoryName: 'HORTIFRUT',
    rows: [
      { key: 'central', label: 'Central' },
      { key: 'iranaya', label: 'Iranaya (Alface)' },
    ],
  },
  {
    key: 'padarias',
    label: 'Padarias',
    type: 'DESPESA',
    categoryName: 'PADARIAS',
    rows: [
      { key: 'madame_formiga', label: 'Madame Formiga' },
      { key: 'jps_panificacao', label: 'JPS Panificacao' },
      { key: 'tradicao_mineira', label: 'Tradicao Mineira' },
      { key: 'chips_aguiar', label: 'Chips Aguiar' },
      { key: 'emporio_ana_clara', label: 'Emporio Ana Clara' },
      { key: 'jaboao_tomaz_aguiar', label: 'Jaboao Tomaz de Aguiar' },
      { key: 'nt_industria', label: 'NT Industria e Comercio' },
      { key: 'nt_cachoeirinha', label: 'NT Cachoeirinha' },
      { key: 'lp_confeitaria', label: 'LP Confeitaria Ltda' },
      { key: 'confeitaria_val', label: 'Confeitaria da Val' },
      { key: 'master_pizza', label: 'Master Pizza' },
    ],
  },
  {
    key: 'sucos',
    label: 'Sucos e Bebidas',
    type: 'DESPESA',
    categoryName: 'SUCOS',
    rows: [
      { key: 'amazonia_polpas', label: 'Amazonia Polpas' },
      { key: 'sorvamel', label: 'Sorvamel' },
      { key: 'sorvetes_megbom', label: 'Sorvetes Megbom Ltda' },
      { key: 'malaga', label: 'Malaga' },
      { key: 'mc_gelados', label: 'MC Comercio Gelados' },
      { key: 'mr_din', label: 'Mr Din da Amazonia' },
      { key: 'n_rodrigues', label: 'N Rodrigues de Sousa Ltda' },
      { key: 'toya', label: 'Toya' },
      { key: 'nutri_sucos', label: 'Nutri Sucos' },
      { key: 'kamby', label: 'Kamby' },
      { key: 'bebidas', label: 'Bebidas' },
    ],
  },
  {
    key: 'nao_alimentar_central',
    label: 'Nao Alimentar Central',
    type: 'DESPESA',
    categoryName: 'NAO_ALIMENTAR_CENTRAL',
    rows: [
      { key: 'descartaveis', label: 'Descartaveis' },
      { key: 'limpeza', label: 'Limpeza' },
    ],
  },
  {
    key: 'nao_alimentar_operacao',
    label: 'Nao Alimentar Operacao',
    type: 'DESPESA',
    categoryName: 'NAO_ALIMENTAR_OPERACAO',
    rows: [
      { key: 'lixo_organico', label: 'Lixo Organico' },
      { key: 'dedetizacao', label: 'Dedetizacao' },
      { key: 'conveniencia_higiene', label: 'Conveniencia Higiene' },
      { key: 'amazon_gas', label: 'Amazon Gas' },
      { key: 'manutencao', label: 'Manutencao' },
      { key: 'epi_fardamento', label: 'EPI/Fardamento' },
      { key: 'cantor', label: 'Cantor' },
      { key: 'decoracao', label: 'Decoracao' },
      { key: 'mat_expediente', label: 'Mat. Expediente' },
      { key: 'utensilios_vv', label: 'Utensilios VV' },
      { key: 'cafe_pratico', label: 'Cafe Pratico (Locacao)' },
      { key: 'pacheco_oliveira', label: 'Pacheco e Oliveira' },
      { key: 'fcx_comercio', label: 'FCX Comercio de Alimentos' },
      { key: 'refrial', label: 'Refrial Distribuidora' },
      { key: 'rent_hotel', label: 'Rent Hotel' },
      { key: 'etiquetas_indent', label: 'Etiquetas Indent' },
      { key: 'qualidade', label: 'Qualidade' },
      { key: 'programacao_eventos', label: 'Programacao/Eventos' },
      { key: 'parcelas_investimentos_3_12', label: 'Parcelas/Investimentos 3/12' },
      { key: 'parcelas_inauguracao_4_12', label: 'Parcelas/Inauguracao 4/12' },
      { key: 'alvara_2025', label: 'Alvara 2025' },
      { key: 'lf_inox', label: 'L F Inox Ind Com' },
      { key: 'jr_rodrigues', label: 'J R Rodrigues (Salmo 91)' },
      { key: 'f_barbosa', label: 'F Barbosa' },
    ],
  },
  {
    key: 'resumo_financeiro',
    label: 'Resumo Financeiro',
    type: 'DESPESA',
    categoryName: 'RESUMO_FINANCEIRO',
    rows: [
      { key: 'massa_salarial', label: 'Massa Salarial' },
      { key: 'encargos_folha', label: 'Encargos sobre a Folha 105%' },
      { key: 'despesa_adm', label: 'Despesa Adm. + Sal. Ind. Outros' },
      { key: 'impostos', label: 'Impostos 9,6%' },
    ],
  },
];
