import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Full Stack Monorepo',
  description: 'Generated by AI as a base monorepo',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`min-h-screen bg-background font-sans antialiased text-foreground`}>
        {children}
      </body>
    </html>
  );
}
